# Generated by Django 3.0.3 on 2020-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=100)),
                ('classnum', models.IntegerField(default=0)),
                ('sect', models.IntegerField(default=0)),
                ('newPriceBookstore', models.FloatField(default=0.0)),
                ('usedPriceBookstore', models.FloatField(default=0.0)),
                ('amazonPrice', models.FloatField(default=0.0)),
                ('amazonLink', models.TextField(max_length=1000)),
                ('isbn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextbookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=100)),
                ('classnum', models.IntegerField(default=0)),
                ('isbn', models.CharField(max_length=100)),
                ('sect', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('negotiable', models.BooleanField(default=True)),
                ('exchangable', models.BooleanField(default=True)),
                ('maxDiff', models.FloatField(default=0.0)),
                ('payment', models.CharField(max_length=200)),
                ('condition', models.IntegerField(default=5)),
                ('additionalInfo', models.TextField(max_length=10000)),
            ],
        ),
    ]
