# Generated by Django 3.0.3 on 2020-02-20 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 22, 44, 56, 97508, tzinfo=utc)),
        ),
    ]
