# Generated by Django 3.0.3 on 2020-02-20 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0002_textbookpost_datepublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 22, 47, 58, 599500, tzinfo=utc)),
        ),
    ]
