# Generated by Django 3.0.3 on 2020-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0003_auto_20200220_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='datePublished',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
