# Generated by Django 3.0.3 on 2020-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0004_auto_20200220_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='format',
            field=models.CharField(default='', max_length=200),
        ),
    ]
