# Generated by Django 3.0.3 on 2020-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0005_textbookpost_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='amazonLink',
            field=models.TextField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='amazonPrice',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='classnum',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='dept',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='newPriceBookstore',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='sect',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='usedPriceBookstore',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='additionalInfo',
            field=models.TextField(default='N/A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='author',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='classnum',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='condition',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='dept',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='exchangable',
            field=models.CharField(default='Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='format',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='isbn',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='maxDiff',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='negotiable',
            field=models.CharField(default='Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='payment',
            field=models.CharField(default='Venmo', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='price',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='sect',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
