# Generated by Django 3.0.3 on 2020-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0007_remove_textbook_amazonprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='amazonLink',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='textbookpost',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
