# Generated by Django 3.0.3 on 2020-02-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0008_auto_20200224_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbookpost',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='textbookpost',
            old_name='datePublished',
            new_name='date_published',
        ),
        migrations.RenameField(
            model_name='textbookpost',
            old_name='maxDiff',
            new_name='max_diff',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='amazonLink',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='newPriceBookstore',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='usedPriceBookstore',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='classnum',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='sect',
        ),
        migrations.RemoveField(
            model_name='textbookpost',
            name='title',
        ),
        migrations.AddField(
            model_name='textbook',
            name='amazon_link',
            field=models.CharField(blank=True, default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='textbook',
            name='new_price_bookstore',
            field=models.CharField(blank=True, default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='textbook',
            name='used_price_bookstore',
            field=models.CharField(blank=True, default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='textbook',
            name='user_created',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='textbookpost',
            name='textbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='txtbook.Textbook'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='classnum',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='dept',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='sect',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
