# Generated by Django 3.0.3 on 2020-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0010_auto_20200227_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='additional_info',
            field=models.TextField(blank=True, default='N/A', max_length=10000),
        ),
    ]
