# Generated by Django 3.0.3 on 2020-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0011_auto_20200228_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
