# Generated by Django 3.0.3 on 2020-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0012_textbookpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
