# Generated by Django 3.0.3 on 2020-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0013_auto_20200301_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
