# Generated by Django 3.0.2 on 2020-03-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0013_auto_20200301_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
