# Generated by Django 3.0.3 on 2020-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0014_auto_20200330_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
