# Generated by Django 3.0.3 on 2020-03-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0015_auto_20200330_0242'),
        ('txtbook', '0014_textbookpost_email'),
    ]

    operations = [
    ]
