# Generated by Django 3.0.3 on 2020-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0016_merge_20200330_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='price',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
