# Generated by Django 3.0.3 on 2020-04-04 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('txtbook', '0018_auto_20200330_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('venmo', models.CharField(max_length=100)),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='txtbook.TextbookPost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
