# Generated by Django 3.0.3 on 2020-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0019_textbookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookuser',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
