# Generated by Django 3.0.3 on 2020-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0021_auto_20200404_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='venmo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
