# Generated by Django 3.0.3 on 2020-04-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0026_auto_20200404_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
