# Generated by Django 3.0.3 on 2020-04-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0027_profile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
