# Generated by Django 3.0.3 on 2020-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0029_auto_20200405_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbookpost',
            name='user',
        ),
    ]
