# Generated by Django 3.0.3 on 2020-04-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0030_remove_textbookpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
