# Generated by Django 3.0.3 on 2020-04-05 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0031_remove_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
