# Generated by Django 3.0.3 on 2020-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0032_profile_post_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post_ids',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='txtbook.TextbookPost'),
        ),
    ]
