# Generated by Django 3.0.3 on 2020-04-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0033_auto_20200405_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='txtbook.TextbookPost'),
        ),
    ]
