# Generated by Django 3.0.3 on 2020-04-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0034_auto_20200407_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, to='txtbook.TextbookPost'),
        ),
    ]
