# Generated by Django 3.0.3 on 2020-04-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0036_auto_20200408_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbookpost',
            name='user',
        ),
        migrations.AddField(
            model_name='textbookpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='txtbook.Profile'),
        ),
    ]
