# Generated by Django 3.0.3 on 2020-04-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0037_auto_20200408_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='txtbook.Profile'),
        ),
    ]
