# Generated by Django 3.0.3 on 2020-04-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0038_auto_20200408_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
