# Generated by Django 3.0.3 on 2020-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0039_textbookpost_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
