# Generated by Django 3.0.3 on 2020-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtbook', '0040_auto_20200413_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
